version: 2

models:
  - name: stg_account
    description: "Staging model for account data"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Account name"


# models:
#   - name: contracts_sfdc       # your model name
#     description: "Contracts enriched with account info"
#     columns:
#       - name: contract_id
#         description: "Unique identifier for the contract"
#         tests:
#           - not_null
#           - unique